apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmpro-middleware
  labels:
    app: mmpro-middleware
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mmpro-middleware
  template:
    metadata:
      labels:
        app: mmpro-middleware
    spec:
      containers:
        - name: mmpro-middleware
          image: <achinthamihiran>/mmpro-middleware:latest  # Replace with your image
          ports:
            - containerPort: 5000  # Replace with the port your app uses
