apiVersion: v1
kind: Service
metadata:
  name: mmpro-middleware-service
spec:
  selector:
    app: mmpro-middleware
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Replace with your container's port
  type: LoadBalancer  # Change to NodePort for local setup
